# Generated by Django 4.0.4 on 2022-06-29 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_discount',
            name='discount_percent',
            field=models.FloatField(default=0),
        ),
    ]
