# Generated by Django 4.0.4 on 2022-06-29 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_discount_discount_percent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product_inventory',
            options={'verbose_name_plural': 'inventory'},
        ),
        migrations.AddField(
            model_name='product_inventory',
            name='vendor',
            field=models.CharField(default='', max_length=255),
        ),
    ]
