# Generated by Django 4.0.4 on 2022-07-01 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_inventory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='product_discount', to='store.product_discount'),
        ),
    ]
