# Generated by Django 4.0.4 on 2022-07-22 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='desc',
            field=models.TextField(blank=True, default="Some quick example text to build on the card title and make up the bulk of the card's content."),
        ),
    ]
