# Generated by Django 4.0.4 on 2022-07-22 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_product_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_inventory',
            name='vendor',
            field=models.CharField(default='Not sepcifc', max_length=255),
        ),
    ]
