# Generated by Django 4.0.6 on 2022-07-29 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created_at',), 'verbose_name': 'Order', 'verbose_name_plural': 'Order'},
        ),
        migrations.AlterModelOptions(
            name='orderitems',
            options={'verbose_name': 'Order Items', 'verbose_name_plural': 'Order Items'},
        ),
        migrations.CreateModel(
            name='OrderShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_status', models.BooleanField(default=False)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=300000, max_digits=12)),
                ('shipping_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_shipping', to='order.order')),
            ],
            options={
                'verbose_name': 'Order Shipping',
                'verbose_name_plural': 'Order Shipping',
            },
        ),
    ]
