# Generated by Django 4.0.6 on 2022-07-29 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_options_alter_orderitems_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordershipment',
            name='order',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='order_shipping', to='order.order'),
        ),
        migrations.AlterField(
            model_name='ordershipment',
            name='shipping_company',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
