# Generated by Django 4.0.6 on 2022-07-30 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_ordershipment_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordershipment',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=30000, max_digits=12),
        ),
    ]
