# Generated by Django 4.0.6 on 2022-08-07 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_ordershipment_shipping_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cost_without_promotion',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='ordershipment',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
